
# mpv keybindings

SPACE cycle pause
f cycle fullscreen
Esc quit-watch-later
q quit-watch-later

l seek 7 exact
h seek -7 exact
k add volume 2
j add volume -2

Shift+l add sub-scale +0.1
Shift+h add sub-scale -0.1
Shift+k add sub-pos -1
Shift+j add sub-pos +1

Alt+l playlist-next
Alt+h playlist-prev

s cycle sub-visibility
Ctrl+s cycle sub

Ctrl+a cycle audio
a cycle mute

Shift+. multiply speed 1.1
Shift+, multiply speed 1/1.1

> add sub-delay +0.1 
< add sub-delay -0.1            

Alt+. add audio-delay 0.100
Alt+, add audio-delay -0.100

Ctrl+r seek 0 absolute
p show-progress
i script-binding stats/display-stats-toggle
o show-text ${playlist}

