include rose-pine.conf

map ctrl+plus change_font_size all +2.0
map ctrl+equal change_font_size all +2.0
map ctrl+kp_add change_font_size all +2.0

map ctrl+minus change_font_size all -2.0
map ctrl+kp_subtract change_font_size all -2.0

font_family	JetBrainsMono Nerd Font
font_size 16.0

window_padding_width 11 12
placement_strategy top-left

background_opacity 0.9
